/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoStrapiRouteImport } from './routes/demo/strapi'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as DemoNeonRouteImport } from './routes/demo/neon'
import { Route as DemoClerkRouteImport } from './routes/demo/clerk'
import { Route as AuthedPaymentSuccessRouteImport } from './routes/_authed/payment-success'
import { Route as AuthedOrdersRouteImport } from './routes/_authed/orders'
import { Route as AuthedCheckoutRouteImport } from './routes/_authed/checkout'
import { Route as AuthedCategoriesRouteImport } from './routes/_authed/categories'
import { Route as AuthedCartRouteImport } from './routes/_authed/cart'
import { Route as DemoStrapiArticleIdRouteImport } from './routes/demo/strapi_.$articleId'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoSentryTestingRouteImport } from './routes/demo/sentry.testing'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiWebhooksClerkRouteImport } from './routes/api/webhooks/clerk'
import { Route as ApiSyncSubcategoriesRouteImport } from './routes/api/sync/subcategories'
import { Route as ApiSyncProductsRouteImport } from './routes/api/sync/products'
import { Route as ApiSyncCategoriesRouteImport } from './routes/api/sync/categories'
import { Route as ApiPaymentXenditWebhookRouteImport } from './routes/api/payment/xendit-webhook'
import { Route as ApiPaymentXenditPaymentRouteImport } from './routes/api/payment/xendit-payment'
import { Route as AuthedProductProductIdRouteImport } from './routes/_authed/product_.$productId'
import { Route as AuthedOrderTransactionIdRouteImport } from './routes/_authed/order_.$transactionId'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStrapiRoute = DemoStrapiRouteImport.update({
  id: '/demo/strapi',
  path: '/demo/strapi',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoNeonRoute = DemoNeonRouteImport.update({
  id: '/demo/neon',
  path: '/demo/neon',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoClerkRoute = DemoClerkRouteImport.update({
  id: '/demo/clerk',
  path: '/demo/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPaymentSuccessRoute = AuthedPaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrdersRoute = AuthedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCheckoutRoute = AuthedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCategoriesRoute = AuthedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCartRoute = AuthedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthedRoute,
} as any)
const DemoStrapiArticleIdRoute = DemoStrapiArticleIdRouteImport.update({
  id: '/demo/strapi_/$articleId',
  path: '/demo/strapi/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSentryTestingRoute = DemoSentryTestingRouteImport.update({
  id: '/demo/sentry/testing',
  path: '/demo/sentry/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksClerkRoute = ApiWebhooksClerkRouteImport.update({
  id: '/api/webhooks/clerk',
  path: '/api/webhooks/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncSubcategoriesRoute = ApiSyncSubcategoriesRouteImport.update({
  id: '/api/sync/subcategories',
  path: '/api/sync/subcategories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncProductsRoute = ApiSyncProductsRouteImport.update({
  id: '/api/sync/products',
  path: '/api/sync/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncCategoriesRoute = ApiSyncCategoriesRouteImport.update({
  id: '/api/sync/categories',
  path: '/api/sync/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentXenditWebhookRoute = ApiPaymentXenditWebhookRouteImport.update({
  id: '/api/payment/xendit-webhook',
  path: '/api/payment/xendit-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentXenditPaymentRoute = ApiPaymentXenditPaymentRouteImport.update({
  id: '/api/payment/xendit-payment',
  path: '/api/payment/xendit-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProductProductIdRoute = AuthedProductProductIdRouteImport.update({
  id: '/product_/$productId',
  path: '/product/$productId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrderTransactionIdRoute =
  AuthedOrderTransactionIdRouteImport.update({
    id: '/order_/$transactionId',
    path: '/order/$transactionId',
    getParentRoute: () => AuthedRoute,
  } as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blocked': typeof BlockedRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/cart': typeof AuthedCartRoute
  '/categories': typeof AuthedCategoriesRoute
  '/checkout': typeof AuthedCheckoutRoute
  '/orders': typeof AuthedOrdersRoute
  '/payment-success': typeof AuthedPaymentSuccessRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/strapi': typeof DemoStrapiRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/order/$transactionId': typeof AuthedOrderTransactionIdRoute
  '/product/$productId': typeof AuthedProductProductIdRoute
  '/api/payment/xendit-payment': typeof ApiPaymentXenditPaymentRoute
  '/api/payment/xendit-webhook': typeof ApiPaymentXenditWebhookRoute
  '/api/sync/categories': typeof ApiSyncCategoriesRoute
  '/api/sync/products': typeof ApiSyncProductsRoute
  '/api/sync/subcategories': typeof ApiSyncSubcategoriesRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/strapi/$articleId': typeof DemoStrapiArticleIdRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blocked': typeof BlockedRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/cart': typeof AuthedCartRoute
  '/categories': typeof AuthedCategoriesRoute
  '/checkout': typeof AuthedCheckoutRoute
  '/orders': typeof AuthedOrdersRoute
  '/payment-success': typeof AuthedPaymentSuccessRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/strapi': typeof DemoStrapiRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/order/$transactionId': typeof AuthedOrderTransactionIdRoute
  '/product/$productId': typeof AuthedProductProductIdRoute
  '/api/payment/xendit-payment': typeof ApiPaymentXenditPaymentRoute
  '/api/payment/xendit-webhook': typeof ApiPaymentXenditWebhookRoute
  '/api/sync/categories': typeof ApiSyncCategoriesRoute
  '/api/sync/products': typeof ApiSyncProductsRoute
  '/api/sync/subcategories': typeof ApiSyncSubcategoriesRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/strapi/$articleId': typeof DemoStrapiArticleIdRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/about': typeof AboutRoute
  '/blocked': typeof BlockedRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/_authed/cart': typeof AuthedCartRoute
  '/_authed/categories': typeof AuthedCategoriesRoute
  '/_authed/checkout': typeof AuthedCheckoutRoute
  '/_authed/orders': typeof AuthedOrdersRoute
  '/_authed/payment-success': typeof AuthedPaymentSuccessRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/strapi': typeof DemoStrapiRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_authed/order_/$transactionId': typeof AuthedOrderTransactionIdRoute
  '/_authed/product_/$productId': typeof AuthedProductProductIdRoute
  '/api/payment/xendit-payment': typeof ApiPaymentXenditPaymentRoute
  '/api/payment/xendit-webhook': typeof ApiPaymentXenditWebhookRoute
  '/api/sync/categories': typeof ApiSyncCategoriesRoute
  '/api/sync/products': typeof ApiSyncProductsRoute
  '/api/sync/subcategories': typeof ApiSyncSubcategoriesRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/strapi_/$articleId': typeof DemoStrapiArticleIdRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blocked'
    | '/contact'
    | '/faq'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/orders'
    | '/payment-success'
    | '/demo/clerk'
    | '/demo/neon'
    | '/demo/store'
    | '/demo/strapi'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/order/$transactionId'
    | '/product/$productId'
    | '/api/payment/xendit-payment'
    | '/api/payment/xendit-webhook'
    | '/api/sync/categories'
    | '/api/sync/products'
    | '/api/sync/subcategories'
    | '/api/webhooks/clerk'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/sentry/testing'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/strapi/$articleId'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blocked'
    | '/contact'
    | '/faq'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/orders'
    | '/payment-success'
    | '/demo/clerk'
    | '/demo/neon'
    | '/demo/store'
    | '/demo/strapi'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/order/$transactionId'
    | '/product/$productId'
    | '/api/payment/xendit-payment'
    | '/api/payment/xendit-webhook'
    | '/api/sync/categories'
    | '/api/sync/products'
    | '/api/sync/subcategories'
    | '/api/webhooks/clerk'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/sentry/testing'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/strapi/$articleId'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/about'
    | '/blocked'
    | '/contact'
    | '/faq'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/_authed/cart'
    | '/_authed/categories'
    | '/_authed/checkout'
    | '/_authed/orders'
    | '/_authed/payment-success'
    | '/demo/clerk'
    | '/demo/neon'
    | '/demo/store'
    | '/demo/strapi'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/_authed/order_/$transactionId'
    | '/_authed/product_/$productId'
    | '/api/payment/xendit-payment'
    | '/api/payment/xendit-webhook'
    | '/api/sync/categories'
    | '/api/sync/products'
    | '/api/sync/subcategories'
    | '/api/webhooks/clerk'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/sentry/testing'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/strapi_/$articleId'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AboutRoute: typeof AboutRoute
  BlockedRoute: typeof BlockedRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TermsRoute: typeof TermsRoute
  DemoClerkRoute: typeof DemoClerkRoute
  DemoNeonRoute: typeof DemoNeonRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoStrapiRoute: typeof DemoStrapiRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiPaymentXenditPaymentRoute: typeof ApiPaymentXenditPaymentRoute
  ApiPaymentXenditWebhookRoute: typeof ApiPaymentXenditWebhookRoute
  ApiSyncCategoriesRoute: typeof ApiSyncCategoriesRoute
  ApiSyncProductsRoute: typeof ApiSyncProductsRoute
  ApiSyncSubcategoriesRoute: typeof ApiSyncSubcategoriesRoute
  ApiWebhooksClerkRoute: typeof ApiWebhooksClerkRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DemoSentryTestingRoute: typeof DemoSentryTestingRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStrapiArticleIdRoute: typeof DemoStrapiArticleIdRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/strapi': {
      id: '/demo/strapi'
      path: '/demo/strapi'
      fullPath: '/demo/strapi'
      preLoaderRoute: typeof DemoStrapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/neon': {
      id: '/demo/neon'
      path: '/demo/neon'
      fullPath: '/demo/neon'
      preLoaderRoute: typeof DemoNeonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/clerk': {
      id: '/demo/clerk'
      path: '/demo/clerk'
      fullPath: '/demo/clerk'
      preLoaderRoute: typeof DemoClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/payment-success': {
      id: '/_authed/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof AuthedPaymentSuccessRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/orders': {
      id: '/_authed/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthedOrdersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/checkout': {
      id: '/_authed/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthedCheckoutRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/categories': {
      id: '/_authed/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthedCategoriesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cart': {
      id: '/_authed/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthedCartRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/demo/strapi_/$articleId': {
      id: '/demo/strapi_/$articleId'
      path: '/demo/strapi/$articleId'
      fullPath: '/demo/strapi/$articleId'
      preLoaderRoute: typeof DemoStrapiArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/sentry/testing': {
      id: '/demo/sentry/testing'
      path: '/demo/sentry/testing'
      fullPath: '/demo/sentry/testing'
      preLoaderRoute: typeof DemoSentryTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/clerk': {
      id: '/api/webhooks/clerk'
      path: '/api/webhooks/clerk'
      fullPath: '/api/webhooks/clerk'
      preLoaderRoute: typeof ApiWebhooksClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/subcategories': {
      id: '/api/sync/subcategories'
      path: '/api/sync/subcategories'
      fullPath: '/api/sync/subcategories'
      preLoaderRoute: typeof ApiSyncSubcategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/products': {
      id: '/api/sync/products'
      path: '/api/sync/products'
      fullPath: '/api/sync/products'
      preLoaderRoute: typeof ApiSyncProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/categories': {
      id: '/api/sync/categories'
      path: '/api/sync/categories'
      fullPath: '/api/sync/categories'
      preLoaderRoute: typeof ApiSyncCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/xendit-webhook': {
      id: '/api/payment/xendit-webhook'
      path: '/api/payment/xendit-webhook'
      fullPath: '/api/payment/xendit-webhook'
      preLoaderRoute: typeof ApiPaymentXenditWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/xendit-payment': {
      id: '/api/payment/xendit-payment'
      path: '/api/payment/xendit-payment'
      fullPath: '/api/payment/xendit-payment'
      preLoaderRoute: typeof ApiPaymentXenditPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/product_/$productId': {
      id: '/_authed/product_/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof AuthedProductProductIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/order_/$transactionId': {
      id: '/_authed/order_/$transactionId'
      path: '/order/$transactionId'
      fullPath: '/order/$transactionId'
      preLoaderRoute: typeof AuthedOrderTransactionIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedCartRoute: typeof AuthedCartRoute
  AuthedCategoriesRoute: typeof AuthedCategoriesRoute
  AuthedCheckoutRoute: typeof AuthedCheckoutRoute
  AuthedOrdersRoute: typeof AuthedOrdersRoute
  AuthedPaymentSuccessRoute: typeof AuthedPaymentSuccessRoute
  AuthedOrderTransactionIdRoute: typeof AuthedOrderTransactionIdRoute
  AuthedProductProductIdRoute: typeof AuthedProductProductIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCartRoute: AuthedCartRoute,
  AuthedCategoriesRoute: AuthedCategoriesRoute,
  AuthedCheckoutRoute: AuthedCheckoutRoute,
  AuthedOrdersRoute: AuthedOrdersRoute,
  AuthedPaymentSuccessRoute: AuthedPaymentSuccessRoute,
  AuthedOrderTransactionIdRoute: AuthedOrderTransactionIdRoute,
  AuthedProductProductIdRoute: AuthedProductProductIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AboutRoute: AboutRoute,
  BlockedRoute: BlockedRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TermsRoute: TermsRoute,
  DemoClerkRoute: DemoClerkRoute,
  DemoNeonRoute: DemoNeonRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoStrapiRoute: DemoStrapiRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiPaymentXenditPaymentRoute: ApiPaymentXenditPaymentRoute,
  ApiPaymentXenditWebhookRoute: ApiPaymentXenditWebhookRoute,
  ApiSyncCategoriesRoute: ApiSyncCategoriesRoute,
  ApiSyncProductsRoute: ApiSyncProductsRoute,
  ApiSyncSubcategoriesRoute: ApiSyncSubcategoriesRoute,
  ApiWebhooksClerkRoute: ApiWebhooksClerkRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DemoSentryTestingRoute: DemoSentryTestingRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStrapiArticleIdRoute: DemoStrapiArticleIdRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
